urls:
  api: 'https://api.dharitri.org'
  swagger:
    - 'https://microservice.dharitri.org'
    - 'https://devnet-microservice.dharitri.org'
    - 'https://testnet-microservice.dharitri.org'
  redis: '127.0.0.1'
database:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  name: 'example'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - utils.dharitri.org
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
