title: config
apps:
  eventsProcessor:
    port: integer
    privatePort: integer
    useCachingInterceptor: boolean
  duneSimulator:
    port: integer
    privatePort: integer
    useCachingInterceptor: boolean
libs:
  common:
    network:
      type: string
      enum: [devnet, testnet, mainnet]
    urls:
      api: string
      dataApiCex: string
      dataApiXexchange: string
      dataApiHatom: string
      duneApi: string
    database:
      host: string
      port: integer
      username:
        type: string
        required: false
      password:
        type: string
        required: false
      name: string
      tlsAllowInvalidCertificates:
        type: boolean
        default: false
    redis:
      host: string
      port: integer
    features:
      dune:
        namespace: string
        apiKey: string
    nativeAuth:
      maxExpirySeconds:
        type: integer
        default: 86400
      acceptedOrigins:
        type: array
        items: string
    security:
      admins:
        type: array
        items: string
        default: []
    rateLimiterSecret:
      type: string
      required: false
