[package]
name = "gas-service-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["contact@dharitri.org"]

[dev-dependencies]

[dependencies.gas-service]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.50.3"
