name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: TerraDharitri/drt-sc-actions/.github/workflows/contracts.yml@v3.3.1
    with:
      rust-toolchain: 1.81.0
      pip-drtpy-args: "dharitri-sdk-cli==v9.7.0"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  tests:
    name: xSuite Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.78.0
          target: wasm32-unknown-unknown

      - name: Install prerequisites
        run: |
          pipx install "dharitri-sdk-cli==v9.7.0"
          
          wget -O binaryen.tar.gz https://github.com/WebAssembly/binaryen/releases/download/version_112/binaryen-version_112-x86_64-linux.tar.gz
          tar -xf binaryen.tar.gz
          cp binaryen-version_112/bin/wasm-opt $HOME/.local/bin

          sudo apt install -y wabt=1.0.27-1

          cargo install wasm-opt
          cargo install twiggy
          
          cargo install dharitri-sc-meta --version 0.50.3 --locked

          which drtpy
          which wasm-opt

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run build
      - run: npm run test
