chainId: 'D'
urls:
  api: 'https://devnet-api.dharitri.org'
  redis: '127.0.0.1'
features:
  transactionProcessor:
    port: 5202
    maxLookBehind: 100
contracts:
  pingPong: 'drt1qqqqqqqqqqqqqpgq72l6vl07fkn3alyfq753mcy4nakm0l72396qtytwhc'
