chainId: 'D'
urls:
  api: 'https://devnet-api.dharitri.org'
  redis: '127.0.0.1'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - https://localhost:3000
    - https://localhost:3001
    - https://localhost:3002
    - https://utils.dharitri.org
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
contracts:
  pingPong: 'drt1qqqqqqqqqqqqqpgq72l6vl07fkn3alyfq753mcy4nakm0l72396qtytwhc'
