// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Promise callbacks:                    1
// Total number of exported functions:  17

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    governance
    (
        init => init
        upgrade => upgrade
        executeProposal => execute_proposal
        withdraw => withdraw
        execute => execute
        withdrawRefundToken => withdraw_refund_token
        getProposalEta => get_proposal_eta
        gateway => gateway
        getMinimumTimeLockDelay => minimum_time_lock_delay
        getGovernanceChain => governance_chain
        getGovernanceAddress => governance_address
        getGovernanceChainHash => governance_chain_hash
        getGovernanceAddressHash => governance_address_hash
        getTimeLockEta => time_lock_eta
        getRefundToken => refund_token
        execute_proposal_callback => execute_proposal_callback
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
