export enum GlobalDataEnum {
  homePageTitle = "Utilities for the Dharitri Blockchain",
  homePageDescription = "This page offers an easy to use pack of utilities necessary for interacting with the Dharitri Blockchain.",
  signatureTxt = "MVX Signature",
  invalidPayload = "invalid-mvx",
  invalidPayloadErr = "Invalid signature payload",
  signature = "94ea7c3c28c2e718cbac76d00423e2cfbde63017120e5353c17b675fb7d78a1e855ee55e41f021d40dad1487db11f5e897c314aaff7d4cc4dc82062abaa97403",
  address = "drt16xlzk48ftvhxp8dyq6d0kkfpgpfechlzycfm9xmdmwna66pvkymq37z0p7",
  signedMsgPlaceHolder = "Insert or paste the message that was signed.",
  signaturePlaceHolder = "Insert or paste the signature. You don't have to add '0x' prefix.",
  confirmationMsg = "Valid",
  invalidMsg = "Invalid",
  base64Err = "Value must be base64 input",
  explainValidUrl = "https://github.com/TerraDharitri/drt-ping-pong-sc/tree/main/ping-pong",
  firstExplainerParagraph = "This Rust",
  errorExplainerMsg = "Could not download git repository.",
  invalidGitUrl = "https://github.com/TerraDharitri/drt-template-dapp",
  abiFile = "abi.json",
  pemFile = "loginPem.pem",
  scAdress = "drt1qqqqqqqqqqqqqpgqk4tchxyrzt5pzunl6qhcnl705yrnplms0n4sqga34s",
  abiPrevieText = "ABI Preview",
  buildInfoLink = "Build Info",
  buildName = "GovernanceV2",
  frameworkName = "dharitri-sc 0.44.0",
  devnetNetwork = "devnet",
  contractFile = "contract.wasm",
}

export enum RoutesEnum {
  converters = "converters",
  auth = "auth",
  signMsg = "sign-message",
  scDeploy = "smart-contract",
  explainer = "explainer",
  login = "unlock",
}
